### PR TITLE
Fix focus after showing a native modal dialog in wxMSW

### LINKED ISSUE #22285: 'SetFocus failed' when closing a "Save changes?" dialog
**Describe the bug**
When closing a "Save changes?" dialog that is displayed when closing a document or exiting the application, an API error will be logged.
```
..\..\src\msw\window.cpp(594): 'SetFocus' failed with error 0x00000057 (Wrong parameter.).
```

It's a regression in wxWidgets-3.1.6.
With wxWidgets-3.1.5 it works without such API error.

**To Reproduce**
The issue can be also reproduced with the **dialogs sample**:
1. Start the dialogs sample.
2. Click on 'Dialogs' > 'Simulate an unsaved document at exit'.
3. Exit via close button [x] in the title bar.
   BTW: If the application is exited via the menu, the "Save changes?" dialog is not displayed.
   This seems to be another bug.
4. Close the displayed "Save changes?" dialog. It doesn't matter how you close it.

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 7 and Windows 10

### PR DESCRIPTION
**Pull request by vadz**
Make some changes to `wxWindowDisabler` and use them to fix #22285.

### CODE REVIEW

File: src/common/utilscmn.cpp [hunk 1]
```diff
@@ -1517,24 +1517,40 @@ wxWindowDisabler::wxWindowDisabler(bool disable)
 {
     m_disabled = disable;
     if ( disable )
+    {
         DoDisable();
+
+#if defined(__WXOSX__) && wxOSX_USE_COCOA
+        AfterDisable(NULL);
```
Comment (vadz) [inline src/common/utilscmn.cpp:1524]: @csomor I'm not sure if we should be doing this, this (may) end(s) up calling `wxGUIEventLoop::BeginModalSession(NULL)` and it's not clear to me if this is really desirable here. I've done it like this because this preserves the behaviour of the original code, but I don't know if it was really intentional.
