### PR TITLE
Fix MSW font dialog in high DPI

### LINKED ISSUE #22313: wxFontDialog displays wrong pointsize in hi-dpi
When using wxFontDialog where I initialize wxFontData with a wxFont, the dialog shows the DPI-adjusted value.

The wxFont has been created at 8pt on a 150% system. The dialog shows 12pt.
myfont.GetPointSize() does report 8.

**Expected vs observed behaviour**
wxFontDialog should display the font size the font was created with, not the adjusted one.

**To Reproduce**
Sample: font
1. Start sample, see point size says 9.0
2. Select->Select Font, dialog shows 14. Cancel
3. In main window, change font size to 12.0, Apply changes.
4. Repeat step2: dialog shows 18 now.

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10.0.19044.1645
 - Main monitor: 150% (monitor 2 is as 200%)

### PR DESCRIPTION
**Pull request by vadz**
This mostly fixes #22313 but also contains a minor improvement to `AutoSystemDpiAware`.

cc @MaartenBent

### CODE REVIEW

File: src/msw/fontdlg.cpp [hunk 1]
```diff
@@ -158,7 +170,24 @@ int wxFontDialog::ShowModal()
...
+        // size, but we're going to overwrite it anyhow, but it's better to use
+        // NULL rather than "this" because it avoids a debug warning about not
+        // being able to determine the correct DPI for this window, due to not
+        // having any valid HWND for it.
+        wxNativeFontInfo nfi(logFont, NULL);
+        nfi.pointSize = wxNativeFontInfo::GetPointSizeAtPPI
+                        (
+                            logFont.lfHeight,
+                            wxDisplay::GetStdPPIValue()
+                        );
```
Comment (MaartenBent) [inline src/msw/fontdlg.cpp:188]: This is wrong. The point size is already correct, it is `lf.lfHeight` that is wrong (based on 96dpi). You could use `WXAdjustToPPI` to fix it, using the dpi determined before calling `AutoSystemDpiAware`.

I'm not sure if it is needed. When the font is used in wxWidgets it is always adjusted to the DPI, but if a user uses the raw font data with `GetNativeFontInfo()` they might get the wrong `lfHeight`.

Comment (vadz) [reply src/msw/fontdlg.cpp:188]: Thanks, this is indeed wrong or, at least, useless, as doing this doesn't change `pointSize` value. I think it's better to use consistent values for `LOGFONT::lfHeight` too, just in case, so I've updated the PR to do it, thanks again for noticing this!

**Comment by dconnet** [comment]
I checked out your branch - it does show the correct pt size now. But now if I ok out and come back in, the font size is now 9 (in my code). In the font dialog, if I use the dialog to select 8pt font, I get 8.5 in the window (I'm not using fractional fonts, so that's probably why I get 9 instead)

**Comment by vadz** [comment]
Sorry, I'm a bit lost: what exactly do I need to do in order to see the problem?

It looks like there is some rounding problem here, but I don't see where exactly...

**Comment by dconnet** [comment]
In the font sample, it starts as 9pt. I use the Select->Select Font (or ctrl+S) to bring up the font selection (it shows 9). Change the size to 8. Ok. The displayed size is now 8.5. Not all point sizes are bigger. 8, 11, 14, 20, 26 (I stopped there)
This is on a 150% monitor.
On 200%, 8->8.2, 10->9.8, 11->11.2, 14->14.2, 16->15.8, 20->20.2 (stopped there)

**Comment by vadz** [comment]
Thanks, I indeed see it too, but this is not related to high DPI and/or my changes, i.e. I believe this was always the case (or since fractional point size support was added, at least).

The reason is that even in standard DPI (96), there is no integer pixel value corresponding to e.g. 10pt size: the exact value would be `10*96/72 == 13.3(3)` but as `LOGFONT::lfHeight` is an int, it gets rounded down to 13. And, converting back to points, `13*72/96 == 9.75` and not 10.

As the native dialog doesn't allow entering fractional sizes, we can just round the resulting point size to the closest integer and I've done this now.

**Comment by dconnet** [comment]
The only issue I'm really seeing now is the sizes that end up at .5. My user has a current font setting of 8. ChooseFont, keep 8. wx returns 8.5, that is being rounded to 9. With dpiAware false or True/PM (and on the 200% monitor), the font stays at 8. But on a 150% screen, I end up in that 8.5 round-trip number.

**Comment by vadz** [comment]
Even after the last commit? It should really be always integer now.

**Comment by dconnet** [comment]
Yes (confirmed by looking at src after pull).
After selecting 8 in the dialog, the following code reports 9.
```
		auto font = dlg.GetFontData().GetChosenFont();
		wxLogDebug(L"PointSize %d", font.GetPointSize());

```
(just to make sure, I did a full compile on wx and my pgm before this post)

**Comment by dconnet** [comment]
Note: You need to be at 150% dpi to see this. 100% or 200% will report back 8.

**Comment by vadz** [comment]
> Note: You need to be at 150% dpi to see this. 100% or 200% will report back 8.

I stupidly forgot about this part, sorry. I do see the problem with 150% DPI, thanks.

**Comment by vadz** [comment]
I think I've really fixed this now by using the point size to determine the pixel height instead of scaling the latter directly, which could result in an accumulation of errors due to rounding.

Please let me know if anybody still sees anything wrong here.

Thanks again for testing!

**Comment by dconnet** [comment]
Much nicer! Thanks! (round tripping now stays consistent)

**Comment by vadz** [comment]
Thanks again for testing!
